--------------------------------TABLES-------------------------------
CREATE TABLE EMPLOYEES (
	EMPL_NAME 	CHAR(50),
	EMPL_OFFICE CHAR(50) NOT NULL,
	EMPL_SALARY INT DEFAULT 100000 CHECK (EMPL_SALARY > 95000),
	EMPL_NUMBER INT,
	EMPL_ID 	INT,
	PRIMARY KEY (EMPL_NAME, EMPL_NUMBER, EMPL_ID)
);

CREATE TABLE CUSTOMERS (
	CUSTOMER_ID INT,
	FIRST_NAME	CHAR(50),
	LAST_NAME	CHAR(50),
	CUSTOM_AGE	INT NOT NULL CHECK (CUSTOM_AGE > 18),
	COUNTRY		CHAR(50) NOT NULL,
	PRIMARY KEY (CUSTOMER_ID, FIRST_NAME, LAST_NAME)
);

CREATE TABLE ORDERS (
	ORDER_ID INT PRIMARY KEY,
	ORDER_ITEM CHAR(50) NOT NULL,
	AMOUNT INT CHECK (AMOUNT > 0),
	CUSTOMER_ID INT,
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID) --NOT WORKING
);

CREATE TABLE DEPARTAMENTS (
	NUM_DPT INTEGER, 
	NOM_DPT CHAR(20), 
	PLANTA INTEGER, 
	EDIFICI CHAR(30), 
	CIUTAT_DPT CHAR(20), 
	PRIMARY KEY (NUM_DPT)
); 

CREATE TABLE PROJECTES (
	NUM_PROJ INTEGER, 
	NOM_PROJ CHAR(10), 
	PRODUCTE CHAR(20), 
	PRESSUPOST INTEGER, 
	PRIMARY KEY (NUM_PROJ)
); 

CREATE TABLE EMPLEATS (
	NUM_EMPL INTEGER, 
	NOM_EMPL CHAR(30), 
	SOU INTEGER, 
	CIUTAT_EMPL CHAR(20), 
	NUM_DPT INTEGER, 
	NUM_PROJ INTEGER, 
	PRIMARY KEY (NUM_EMPL), 
	FOREIGN KEY (NUM_DPT) REFERENCES DEPARTAMENTS (NUM_DPT), 
	FOREIGN KEY (NUM_PROJ) REFERENCES PROJECTES (NUM_PROJ)
); 

-----Drop tables-----
DROP TABLE EMPLOYEES;
DROP TABLE DEPARTAMENTS CASCADE;
DROP TABLE PROJECTES CASCADE;
DROP TABLE EMPLEATS;
DROP TABLE CUSTOMERS;
DROP TABLE ORDERS;

-------------    INSERTING VALUES INTO EMPLOYEES     ----------------
INSERT INTO EMPLOYEES VALUES ('RICARDO', 'OMEGA', 250000, 1, 5224568);
INSERT INTO EMPLOYEES VALUES ('JULIA', 'VERTEX', 150000, 4, 6454564);
INSERT INTO EMPLOYEES VALUES ('BEATRIZ', 'OMEGA', 450000, 2, 1234579);
INSERT INTO EMPLOYEES VALUES ('CALAMARDO', 'TRIANGLE', 153000, 3, 1334111);
INSERT INTO EMPLOYEES VALUES ('ROSA', 'PISA', 150400, 5, 5554132);
INSERT INTO EMPLOYEES VALUES ('MARIA', 'TRIANGLE', 100000, 9, 2554000);
INSERT INTO EMPLOYEES VALUES ('MICHAEL', 'PISA', 120000, 8, 6434166);
INSERT INTO EMPLOYEES VALUES ('GREGORIO', 'NORD', 97000, 0, 6441555);
INSERT INTO EMPLOYEES VALUES ('ONGOMBO', 'DELTA', 125000, 14, 9114011);
INSERT INTO EMPLOYEES VALUES ('VÍCTOR', 'DELTA', 133000, 13, 7775111);
INSERT INTO EMPLOYEES VALUES ('KATE', 'OMEGA', 144500, 10, 8110101);
INSERT INTO EMPLOYEES VALUES ('CATARINA', 'ALPHA', 255000, 12, 8114795);
INSERT INTO EMPLOYEES VALUES ('YUMEKO', 'APLHA', 400000, 11, 1237774);
INSERT INTO EMPLOYEES VALUES ('YEN', 'BETA', 300000, 7, 7115382);
INSERT INTO EMPLOYEES VALUES ('POO', 'BETA', 400000, 6, 2223911);
INSERT INTO EMPLOYEES VALUES ('ESTEBAN', 'APLHA', 550000, 10, 3382771);

-------------    INSERTING VALUES INTO DEPARTAMENTS     ----------------
INSERT INTO  DEPARTAMENTS VALUES (5,'VENDES',3,'MUNTANER','MADRID'); 
INSERT INTO  DEPARTAMENTS VALUES (6,'COMPRES',3,'PONT NOU','MANRESA');

INSERT INTO  DEPARTAMENTS VALUES (5,'VENDES',3,'MUNTANER','BARCELONA'); 
INSERT INTO  DEPARTAMENTS VALUES (6,'COMPRES',4,'ARIBAU','BARCELONA'); 
INSERT INTO  DEPARTAMENTS VALUES (7,'RECURSOS HUMANS',2,'PONT','MANRESA'); 
INSERT INTO  DEPARTAMENTS VALUES (8,'MANTENIMENT',8,'RIU NOU','MANRESA'); 

-------------    INSERTING VALUES INTO EMPLEATS    ----------------
INSERT INTO  EMPLEATS VALUES (3,'MANEL',250000,'MADRID',5,null); 
INSERT INTO  EMPLEATS VALUES (4,'ANNA', 350000,'ALCOVENDAS',5,null);

INSERT INTO  EMPLEATS VALUES (3,'MANEL',250000,'CORNELLA',5,null); 
INSERT INTO  EMPLEATS VALUES (4,'ANNA', 350000,'HOSPITALET',5,null); 
INSERT INTO  EMPLEATS VALUES (5,'ROSER',300000,'CORNELLA',6,null); 
INSERT INTO  EMPLEATS VALUES (6,'RAUL', 150000,'CORNELLA',6,null); 
INSERT INTO  EMPLEATS VALUES (7,'PAU',300000,'BARCELONA',7,null); 
INSERT INTO  EMPLEATS VALUES (8,'ANDREA', 150000,'BADALONA',7,null); 

--Exercici 2 test
INSERT INTO  EMPLEATS VALUES (1,'PAU',300000,'BARCELONA',8,null);

--------------      UPDATE QUERIES     --------------
UPDATE EMPLOYEES SET EMPL_SALARY = 135000 WHERE EMPL_NAME = 'GREGORIO';


--------------SPECIFY QUERY EXECUTION--------------
EXPLAIN SELECT * FROM EMPLOYEES ORDER BY EMPL_NAME;

--------------SELECT QUERY EXECUTIONS--------------
SELECT * FROM EMPLOYEES ORDER BY EMPL_NAME;
--Total salary of employees with salary between 100000 and 300000
SELECT SUM(EMPL_SALARY) AS TOTAL FROM EMPLOYEES WHERE EMPL_SALARY BETWEEN 100000 AND 300000;
--Amount of employees at each office
SELECT EMPL_OFFICE, COUNT(*) AS AMOUNT FROM EMPLOYEES GROUP BY EMPL_OFFICE;
--The offices where there's at least 2 employees
SELECT EMPL_OFFICE, COUNT(*) AS AMOUNT FROM EMPLOYEES GROUP BY EMPL_OFFICE HAVING COUNT(*) > 1;
--Offices that have at least 2 employees
SELECT EMPL_OFFICE, COUNT(*) AS AMOUNT FROM EMPLOYEES GROUP BY EMPL_OFFICE HAVING COUNT(*) > 1;
--Empleats que viuen a barcelona
SELECT DISTINCT NOM_EMPL FROM EMPLEATS WHERE CIUTAT_EMPL = 'BARCELONA';
--Tots els empleats listats per ciutats on viuen 
SELECT NOM_EMPL, CIUTAT_EMPL FROM EMPLEATS GROUP BY CIUTAT_EMPL, NOM_EMPL; 

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTAMENTS;
SELECT * FROM EMPLEATS;
SELECT * FROM PROJECTES; 

SELECT * FROM DEPARTAMENTS, EMPLEATS;
SELECT * FROM DEPARTAMENTS NATURAL INNER JOIN EMPLEATS;

-------- EXERCICIS DOCUMENT REPÀS BD PARCIAL 1 ------------

---- EXERCICI 1 ----
--Consulta 2
SELECT *
FROM EMPLEATS E NATURAL INNER JOIN DEPARTAMENTS D
WHERE D.CIUTAT_DPT = 'MADRID' AND E.SOU > 200000;

--Consulta 3
SELECT E.NUM_EMPL, E.NOM_EMPL, D.NUM_DPT, D.NOM_DPT 
FROM EMPLEATS E NATURAL INNER JOIN DEPARTAMENTS D
WHERE D.CIUTAT_DPT = 'MADRID' AND E.SOU > 200000;

--Consulta 4
SELECT D.NUM_DPT, D.NOM_DPT
FROM EMPLEATS E NATURAL INNER JOIN DEPARTAMENTS d 
WHERE D.CIUTAT_DPT = 'MADRID' AND E.SOU > 200000;

--Per què en la consulta 4 no surt el departament amb ID 6?

-->Perquè el departament 6 no està situat a MADRID, com que fem
--natural inner join es combinen totes duas taules de tal manera
--que tenim la taula departaments "just a la dreta" de la taula 
--empleats i tots els atributs que s'anomenen iguals (i.e num_dpt)
--es descarten els de departaments i només es té en compte els de empleats

---- EXERCICI 2 ----
SELECT D.CIUTAT_DPT, COUNT(*)
FROM EMPLEATS E NATURAL INNER JOIN DEPARTAMENTS D
WHERE E.SOU > 200000
GROUP BY D.CIUTAT_DPT;

--Pensar si hi pot haver un contingut de la base de dades que faci que 
--la consulta doni resultats repetits?

--La consulta ens diu quants empleats hi ha a la ciutat de departament X
--amb sou més gran que 200000. Hi pot haver repetits. En el cas de que un
--empleats tingui assignat més d'un departament aleshores s'el contará dues vegades
--la solució seria que 'fem UNIQUE' l'atribut NOM_EMPLEAT

SELECT D.CIUTAT_DPT, COUNT(DISTINCT E.NOM_EMPL)
FROM EMPLEATS E NATURAL INNER JOIN DEPARTAMENTS D
WHERE E.SOU > 200000
GROUP BY D.CIUTAT_DPT;

--Consulta 5
SELECT D.CIUTAT_DPT, COUNT(*)
FROM EMPLEATS E NATURAL INNER JOIN DEPARTAMENTS D
WHERE E.SOU > 200000
GROUP BY D.CIUTAT_DPT, D.EDIFICI;

--Pensar si hi pot haver un contingut de la base de dades que faci que la 
--consulta doni resultats repetits. 
--Hi poden haver repetits en aquesta consulta si a la taula departaments 
--tenim dos departaments a la mateiza ciutat però a edifcis diferents.

--Pensar en quin és el significat de les dades que estem obtenint com a 
--resultat d’aquesta consulta. 
--La consulta ens retorna els departaments on hi ha empleats que cobren
--més de 200000 i tenen un departament en la mateixa ciutat i edifici

--Consulta 8
SELECT COUNT(*)
FROM EMPLEATS E NATURAL INNER JOIN DEPARTAMENTS D
WHERE E.SOU > 200000;

--Pensar si hi pot haver un contingut de la base de dades que faci que la 
--consulta doni resultats repetits...
--La consulta ens retorna els empleats que cobren més de 200000, si un empleats 
--té assignat més d'un departament la consulta dona valors repetits

SELECT * FROM EMPLEATS, DEPARTAMENTS;
SELECT * FROM EMPLEATS NATURAL INNER JOIN DEPARTAMENTS;

...

--------------REL. ALGEB QUERY EXECUTIONS--------------

#R = EMPLOYEES(EMPL_SALARY < 300000);

