CREATE TABLE DEPARTAMENTS
         (	NUM_DPT INTEGER,
	NOM_DPT CHAR(20),
	PLANTA INTEGER,
	EDIFICI CHAR(30),
	CIUTAT_DPT CHAR(20),
	PRIMARY KEY (NUM_DPT));

CREATE TABLE PROJECTES
         (	NUM_PROJ INTEGER,
	NOM_PROJ CHAR(10),
	PRODUCTE CHAR(20),
	PRESSUPOST INTEGER,
	PRIMARY KEY (NUM_PROJ));

CREATE TABLE EMPLEATS
         (	NUM_EMPL INTEGER,
	NOM_EMPL CHAR(30),
	SOU INTEGER,
	CIUTAT_EMPL CHAR(20),
	NUM_DPT INTEGER,
	NUM_PROJ INTEGER,
	PRIMARY KEY (NUM_EMPL),
	FOREIGN KEY (NUM_DPT) REFERENCES DEPARTAMENTS (NUM_DPT),
	FOREIGN KEY (NUM_PROJ) REFERENCES PROJECTES (NUM_PROJ));

INSERT INTO  DEPARTAMENTS VALUES (3,'MARKETING',2,'PAU CLARIS','BARCELONA');

INSERT INTO  PROJECTES VALUES (1,'IBDTEL','TELEVISIO',1000000);

INSERT INTO  EMPLEATS VALUES (4,'JOAN',30000,'BARCELONA',3,1);

INSERT INTO  EMPLEATS VALUES (5,'PERE',25000,'MATARO',3,1);

DROP TABLE EMPLEATS;
DROP TABLE PROJECTES;
DROP TABLE DEPARTAMENTS;

/*
 * Doneu una sentència SQL per obtenir els números i els noms dels 
 * projectes que tenen assignats dos o més empleats.
 * Cal ordenar el resultat descendement per número de projecte.
 * Pel joc de proves que trobareu al fitxer adjunt, la sortida seria:

NUM_PROJ		NOM_PROJ
1		IBDTEL
 * */
SELECT p.num_proj, p.nom_proj
FROM empleats e, projectes p
WHERE e.num_proj = p.num_proj
GROUP BY p.num_proj
HAVING COUNT(*) >= 2
ORDER BY p.num_proj DESC;
