CREATE TABLE DEPARTAMENTS
         (	NUM_DPT INTEGER,
	NOM_DPT CHAR(20),
	PLANTA INTEGER,
	EDIFICI CHAR(30),
	CIUTAT_DPT CHAR(20),
	PRIMARY KEY (NUM_DPT));

CREATE TABLE PROJECTES
         (	NUM_PROJ INTEGER,
	NOM_PROJ CHAR(10),
	PRODUCTE CHAR(20),
	PRESSUPOST INTEGER,
	PRIMARY KEY (NUM_PROJ));

CREATE TABLE EMPLEATS
         (	NUM_EMPL INTEGER,
	NOM_EMPL CHAR(30),
	SOU INTEGER,
	CIUTAT_EMPL CHAR(20),
	NUM_DPT INTEGER,
	NUM_PROJ INTEGER,
	PRIMARY KEY (NUM_EMPL),
	FOREIGN KEY (NUM_DPT) REFERENCES DEPARTAMENTS (NUM_DPT),
	FOREIGN KEY (NUM_PROJ) REFERENCES PROJECTES (NUM_PROJ));

INSERT INTO  DEPARTAMENTS VALUES (5,'VENDES', 3,'MUNTANER', 'MADRID');
INSERT INTO  DEPARTAMENTS VALUES (6,'TRASNPORT', 4,'OMEGA', 'BARCELONA');
INSERT INTO  DEPARTAMENTS VALUES (7,'IMATGE', 5,'VÈRTEX', 'LA MANCHA');

INSERT INTO  EMPLEATS VALUES (3, 'MANEL', 250000,'MADRID', 5, null);
INSERT INTO  EMPLEATS VALUES (4, 'GABI', 310000,'MADRID', 5, null);
INSERT INTO  EMPLEATS VALUES (6, 'TOMÁS', 280000,'BARCELONA', 6, null);
INSERT INTO  EMPLEATS VALUES (8, 'CARLOS', 190000,'LEÓN', 5, null);
INSERT INTO  EMPLEATS VALUES (7, 'HUGO', 400000,'MADRID', 5, null);
INSERT INTO  EMPLEATS VALUES (9, 'VÍCTOR', 410000,'MURICA', 7, null);

select d.num_dpt, d.nom_dpt, avg(e.sou) 
from departaments d, empleats e 
where d.ciutat_dpt = 'MADRID' and d.num_dpt = e.num_dpt group by d.num_dpt;

select d.num_dpt, d.nom_dpt, avg(e.sou) 
from departaments d, empleats e 
where d.num_dpt = e.num_dpt group by d.num_dpt;



