CREATE TABLE DEPARTAMENTS
         (	NUM_DPT INTEGER,
	NOM_DPT CHAR(20),
	PLANTA INTEGER,
	EDIFICI CHAR(30),
	CIUTAT_DPT CHAR(20),
	PRIMARY KEY (NUM_DPT));

CREATE TABLE PROJECTES
         (	NUM_PROJ INTEGER,
	NOM_PROJ CHAR(10),
	PRODUCTE CHAR(20),
	PRESSUPOST INTEGER,
	PRIMARY KEY (NUM_PROJ));

CREATE TABLE EMPLEATS
         (	NUM_EMPL INTEGER,
	NOM_EMPL CHAR(30),
	SOU INTEGER,
	CIUTAT_EMPL CHAR(20),
	NUM_DPT INTEGER,
	NUM_PROJ INTEGER,
	PRIMARY KEY (NUM_EMPL),
	FOREIGN KEY (NUM_DPT) REFERENCES DEPARTAMENTS (NUM_DPT),
	FOREIGN KEY (NUM_PROJ) REFERENCES PROJECTES (NUM_PROJ));

INSERT INTO  DEPARTAMENTS VALUES (3,'MARKETING',3,'VERDAGUER','VIC');
INSERT INTO  DEPARTAMENTS VALUES (2,'VENDES',5,'GIRO','BARCELONA');
INSERT INTO  DEPARTAMENTS VALUES (1,'IMATGE',2,'OMEGA','MADRID');
INSERT INTO  DEPARTAMENTS VALUES (4,'TRANSPORT',6,'VERTEX','TARRAGONA');

INSERT INTO  PROJECTES VALUES (1,'IBDTEL','TELEVISIO',1000000);

INSERT INTO  EMPLEATS VALUES (3,'ROBERTO',25000,'MADRID',3,1);
INSERT INTO  EMPLEATS VALUES (2,'DAVID',27000,'GIRONA',4,1);
INSERT INTO  EMPLEATS VALUES (1,'CARLOS',22400,'NEW YORK',2,1);
INSERT INTO  EMPLEATS VALUES (4,'ANDRÉS',28000,'W.D.C',4,1);
INSERT INTO  EMPLEATS VALUES (5,'CARLA',21000,'W.D.C',3,1);
INSERT INTO  EMPLEATS VALUES (6,'MARC',19000,'W.D.C',3,1);
INSERT INTO  EMPLEATS VALUES (7,'HUGO',30000,'KYOTO',1,1);
INSERT INTO  EMPLEATS VALUES (8,'TONI',31000,'KYOTO',1,1);
INSERT INTO  EMPLEATS VALUES (9,'GERALT',40000,'TARRAGONA',3,1);
INSERT INTO  EMPLEATS VALUES (10,'BRUC',12000,'MANRESA',4,1);
INSERT INTO  EMPLEATS VALUES (11,'DILMA',11000,'MADRID',4,1);
INSERT INTO  EMPLEATS VALUES (12,'KRAIT',13000,'TERRASSA',3,1);
INSERT INTO  EMPLEATS VALUES (13,'SIAX',21700,'TERRASSA',2,1);

--Solució:
#A=EMPLEATS(CIUTAT_EMPL='MADRID')
B=EMPLEATS(CIUTAT_EMPL!='MADRID')
C=A[num_dpt]
D=B[num_dpt]
E=C-D
F=E*departaments
G=F[num_dpt, nom_dpt];